name: Other
description: Anything that doesn't fit the other templates.
title: "[other] "
body:
  - type: textarea
    id: body
    attributes:
      label: What's up?
    validations:
      required: true
